language: python
python:
  - 2.7
  - 3.4
  - 3.5

env:
  - DJANGO='django>=1.8,<1.9'
  - DJANGO='django>=1.9'

install:
  - pip install -q $DJANGO pytz
  - pip install coveralls

script:
    coverage run --source=unixtimestampfield setup.py test

after_success:
  coveralls

notifications:
  email:
    recipients:
      - ymy1019@gmail.com
